# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c14a4599092e916428810b71e9c2a09dbe551c860570aa46abeffe96963d413b2209162abf0160fe386ac20cf7498a1c387e4ff46012a5a534fa6b0f48dd5db6

test:
  secret_key_base: eb647cc2cf6db9be7ce0bc940b0ff5a5e0d8ff7d325c950eb56559649f2c366ffd3c88c32908742b23d0f8a0df80920bf84db6f6a1a1bdf7616731fb65657420

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
